import { redirect } from "next/navigation";
import { Activity, Bell, CircleDollarSign, ContactRound, LayoutDashboard, Search, Settings, Target, UsersRound, CheckSquare, Plus, Building2 } from "lucide-react";
import { createClient } from "../../lib/supabase/server";
import { logout } from "../auth/actions";
import { createDeal, updateDealStage } from "./actions";

const nav=[["Overview",LayoutDashboard,"/dashboard"],["Leads",ContactRound,"/dashboard#leads"],["Customers",UsersRound,"/customers"],["Deals",CircleDollarSign,"/deals"],["Tasks",CheckSquare,"#"],["Activity",Activity,"#"]] as const;
const stages=[["prospecting","Prospecting"],["qualified","Qualified"],["proposal","Proposal"],["negotiation","Negotiation"],["won","Won"],["lost","Lost"]] as const;

export default async function DealsPage({searchParams}:{searchParams?:{q?:string;created?:string;error?:string}}){
 const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:profile}=await supabase.from("profiles").select("full_name,role").eq("id",user.id).single();
 const q=(searchParams?.q||"").trim();
 let dq=supabase.from("deals").select("id,title,value,stage,created_at,customer_id,customers(name,company)").order("created_at",{ascending:false});
 if(q) dq=dq.ilike("title",`%${q}%`);
 const [{data:deals},{data:customers},{count:leadCount}]=await Promise.all([dq,supabase.from("customers").select("id,name,company").order("name"),supabase.from("leads").select("*",{count:"exact",head:true})]);
 const rows=(deals||[]) as any[]; const open=rows.filter(d=>!["won","lost"].includes(d.stage)); const won=rows.filter(d=>d.stage==="won");
 const pipeline=open.reduce((s,d)=>s+Number(d.value||0),0), wonValue=won.reduce((s,d)=>s+Number(d.value||0),0);
 const name=profile?.full_name||user.email?.split("@")[0]||"User"; const initials=name.split(" ").map((x:string)=>x[0]).slice(0,2).join("").toUpperCase();
 const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
 return <main className="crm-app"><aside className="crm-sidebar"><div className="crm-brand"><span><Target size={19}/></span><strong>Pipeline<i>OS</i></strong></div><nav>{nav.map(([label,Icon,href])=><a key={label} className={label==="Deals"?"active":""} href={href}><Icon size={18}/><span>{label}</span>{label==="Leads"&&<b>{leadCount||0}</b>}</a>)}</nav><div className="sidebar-bottom"><a href="#"><Settings size={18}/><span>Settings</span></a><div className="user-chip"><span>{initials}</span><div><strong>{name}</strong><small>{profile?.role||"sales"}</small></div></div></div></aside>
 <section className="crm-content"><header className="crm-topbar"><form className="global-search" action="/deals"><Search size={17}/><input name="q" defaultValue={q} placeholder="Search deals..."/><kbd>⌘ K</kbd></form><div className="top-actions"><button className="icon-button"><Bell size={18}/></button><form action={logout}><button className="text-button">Sign out</button></form></div></header>
 <div className="crm-page deals-page"><div className="welcome-row"><div><span className="page-kicker">REVENUE PIPELINE</span><h1>Deals</h1><p>Move opportunities from first conversation to closed revenue.</p></div><a href="#new-deal" className="add-lead"><Plus size={17}/> New deal</a></div>
 {searchParams?.created&&<div className="success-banner">Deal created successfully. Your pipeline is updated.</div>}{searchParams?.error&&<div className="error-banner">{searchParams.error}</div>}
 <section className="deal-metrics"><article><span>Pipeline value</span><strong>{money(pipeline)}</strong><small>{open.length} active opportunities</small></article><article><span>Won revenue</span><strong>{money(wonValue)}</strong><small>{won.length} closed won</small></article><article><span>Total deals</span><strong>{rows.length}</strong><small>Across all stages</small></article><article><span>Customers</span><strong>{customers?.length||0}</strong><small>Available relationships</small></article></section>
 <section className="deals-layout"><div className="deal-board">{stages.map(([key,label])=>{const items=rows.filter(d=>d.stage===key);const total=items.reduce((s,d)=>s+Number(d.value||0),0);return <div className="deal-column" key={key}><div className="deal-column-head"><div><span className={`stage-dot ${key}`}/><strong>{label}</strong><b>{items.length}</b></div><small>{money(total)}</small></div><div className="deal-stack">{items.map(d=><article className="pipeline-deal" key={d.id}><div className="deal-card-title"><strong>{d.title}</strong><span>{money(Number(d.value||0))}</span></div><p><Building2 size={13}/>{d.customers?.company||d.customers?.name||"Unassigned customer"}</p><form action={updateDealStage}><input type="hidden" name="id" value={d.id}/><select name="stage" defaultValue={d.stage}>{stages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button>Move</button></form></article>)}</div></div>})}</div>
 <aside className="new-deal-card" id="new-deal"><div className="panel-head"><div><h2>Create deal</h2><p>Add a real opportunity</p></div><div className="quick-icon"><Plus size={18}/></div></div><form action={createDeal} className="lead-form"><label>Deal title<input name="title" placeholder="e.g. Website redesign" required/></label><label>Customer<select name="customer_id" required defaultValue=""><option value="" disabled>Select customer</option>{customers?.map((c:any)=><option key={c.id} value={c.id}>{c.name}{c.company?` — ${c.company}`:""}</option>)}</select></label><label>Deal value (USD)<input name="value" type="number" min="0" step="0.01" placeholder="12000" required/></label><label>Stage<select name="stage" defaultValue="prospecting">{stages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><button type="submit" disabled={!customers?.length}><Plus size={16}/> Create deal</button>{!customers?.length&&<small>Convert a qualified lead into a customer first.</small>}</form></aside></section></div></section></main>;
}