import { redirect } from "next/navigation";
import { Activity, Bell, CircleDollarSign, ContactRound, LayoutDashboard, Plus, Search, Settings, Target, UsersRound, CheckSquare, MoreHorizontal, TrendingUp } from "lucide-react";
import { createClient } from "../../lib/supabase/server";
import { logout } from "../auth/actions";
import { convertLeadToCustomer, createLead, deleteLead, updateLeadStatus } from "./actions";

const nav = [["Overview",LayoutDashboard],["Leads",ContactRound],["Customers",UsersRound],["Deals",CircleDollarSign],["Tasks",CheckSquare],["Activity",Activity]] as const;

export default async function DashboardPage({searchParams}:{searchParams?:{q?:string;lead_added?:string;lead_error?:string}}){
 const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:profile}=await supabase.from("profiles").select("full_name, role").eq("id",user.id).single();
 const q=(searchParams?.q||"").trim(); let leadQuery=supabase.from("leads").select("id,name,email,phone,company,status,created_at").order("created_at",{ascending:false}).limit(8);
 if(q) leadQuery=leadQuery.or(`name.ilike.%${q}%,company.ilike.%${q}%,email.ilike.%${q}%`);
 const [lr,lc,cc,dc,tc,qc]=await Promise.all([leadQuery,supabase.from("leads").select("*",{count:"exact",head:true}),supabase.from("customers").select("*",{count:"exact",head:true}),supabase.from("deals").select("*",{count:"exact",head:true}),supabase.from("tasks").select("*",{count:"exact",head:true}).eq("completed",false),supabase.from("leads").select("*",{count:"exact",head:true}).eq("status","qualified")]);
 const leads=lr.data||[]; const name=profile?.full_name||user.email?.split("@")[0]||"there"; const initials=name.split(" ").map((x:string)=>x[0]).slice(0,2).join("").toUpperCase();
 return <main className="crm-app"><aside className="crm-sidebar"><div className="crm-brand"><span><Target size={19}/></span><strong>Pipeline<i>OS</i></strong></div><nav>{nav.map(([label,Icon],i)=><a key={label} className={i===0?"active":""} href={label==="Overview"?"/dashboard":label==="Customers"?"/customers":label==="Deals"?"/deals":"#leads"}><Icon size={18}/><span>{label}</span>{label==="Leads"&&<b>{lc.count||0}</b>}</a>)}</nav><div className="sidebar-bottom"><a href="#"><Settings size={18}/><span>Settings</span></a><div className="user-chip"><span>{initials}</span><div><strong>{name}</strong><small>{profile?.role||"sales"}</small></div></div></div></aside>
 <section className="crm-content"><header className="crm-topbar"><form className="global-search" action="/dashboard"><Search size={17}/><input name="q" defaultValue={q} placeholder="Search leads, companies..."/><kbd>⌘ K</kbd></form><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={18}/><i/></button><form action={logout}><button className="text-button">Sign out</button></form></div></header>
 <div className="crm-page"><div className="welcome-row"><div><span className="page-kicker">SALES OVERVIEW</span><h1>Good morning, {name.split(" ")[0]}.</h1><p>Here’s what’s happening across your pipeline today.</p></div><a href="#new-lead" className="add-lead"><Plus size={17}/> Add lead</a></div>
 {searchParams?.lead_added&&<div className="success-banner">Lead added successfully. Your pipeline is up to date.</div>}{searchParams?.lead_error&&<div className="error-banner">{searchParams.lead_error}</div>}
 <section className="crm-stats"><article><div className="stat-icon purple"><ContactRound size={19}/></div><span>Total leads</span><strong>{lc.count||0}</strong><small><TrendingUp size={13}/> Live from Supabase</small></article><article><div className="stat-icon blue"><UsersRound size={19}/></div><span>Customers</span><strong>{cc.count||0}</strong><small>Converted relationships</small></article><article><div className="stat-icon green"><CircleDollarSign size={19}/></div><span>Open deals</span><strong>{dc.count||0}</strong><small>Active opportunities</small></article><article><div className="stat-icon amber"><CheckSquare size={19}/></div><span>Open tasks</span><strong>{tc.count||0}</strong><small>{qc.count||0} qualified leads</small></article></section>
 <section className="crm-grid"><div className="leads-panel" id="leads"><div className="panel-head"><div><h2>Recent leads</h2><p>Latest prospects in your workspace</p></div><span className="panel-count">{lc.count||0} total</span></div>
 {leads.length?<div className="lead-table"><div className="lead-row lead-header"><span>Lead</span><span>Company</span><span>Status</span><span>Created</span><span/></div>{leads.map((lead:any)=><div className="lead-row" key={lead.id}><span className="lead-person"><i>{lead.name.slice(0,2).toUpperCase()}</i><span><strong>{lead.name}</strong><small>{lead.email||lead.phone||"No contact yet"}</small></span></span><span>{lead.company||"—"}</span><form action={updateLeadStatus}><input type="hidden" name="id" value={lead.id}/><select name="status" defaultValue={lead.status}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="converted">Converted</option><option value="lost">Lost</option></select><button className="mini-save">Save</button></form><span className="date-cell">{new Date(lead.created_at).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span><div className="lead-actions">{lead.status==="qualified"&&<form action={convertLeadToCustomer}><input type="hidden" name="id" value={lead.id}/><button className="convert-button">Convert</button></form>}<form action={deleteLead}><input type="hidden" name="id" value={lead.id}/><button className="more-button" title="Delete lead"><MoreHorizontal size={17}/></button></form></div></div>)}</div>:<div className="empty-state"><div><ContactRound size={25}/></div><h3>Your pipeline is ready.</h3><p>Add your first lead to start testing the real CRM workflow.</p><a href="#new-lead">Add first lead <Plus size={14}/></a></div>}</div>
 <aside className="new-lead-card" id="new-lead"><div className="panel-head"><div><h2>Quick add</h2><p>Create a new lead</p></div><div className="quick-icon"><Plus size={18}/></div></div><form action={createLead} className="lead-form"><label>Full name<input name="name" placeholder="e.g. Sarah Khan" required/></label><label>Company<input name="company" placeholder="Company name"/></label><div className="form-split"><label>Email<input name="email" type="email" placeholder="name@company.com"/></label><label>Phone<input name="phone" placeholder="+1 555..."/></label></div><label>Status<select name="status" defaultValue="new"><option value="new">New lead</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option></select></label><button type="submit"><Plus size={16}/> Create lead</button><small>Protected by owner-scoped Row Level Security.</small></form></aside></section></div></section></main>;
}